"""add_quality_score_to_summaries

Revision ID: 58aaa9db54d5
Revises: 61823b0802e3
Create Date: 2025-09-24 13:52:45.211654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58aaa9db54d5'
down_revision = '61823b0802e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_summaries', sa.Column('quality_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_summaries', 'quality_score')
    # ### end Alembic commands ###