"""add_app_config_table

Revision ID: 5d8b22e580b2
Revises: c384dca408e6
Create Date: 2025-09-24 21:08:04.473061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8b22e580b2'
down_revision = 'c384dca408e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('app_config', 'value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.create_index(op.f('ix_app_config_key'), 'app_config', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_config_key'), table_name='app_config')
    op.alter_column('app_config', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('app_config', 'created_at')
    # ### end Alembic commands ###